/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package swaggerdemo.restapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TodoItem model.
 */
public class TodoItem {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private Long id;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The isComplete property.
     */
    @JsonProperty(value = "isComplete")
    private Boolean isComplete;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public Long id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the TodoItem object itself.
     */
    public TodoItem withId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the TodoItem object itself.
     */
    public TodoItem withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the isComplete value.
     *
     * @return the isComplete value
     */
    public Boolean isComplete() {
        return this.isComplete;
    }

    /**
     * Set the isComplete value.
     *
     * @param isComplete the isComplete value to set
     * @return the TodoItem object itself.
     */
    public TodoItem withIsComplete(Boolean isComplete) {
        this.isComplete = isComplete;
        return this;
    }

}
