/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the TodoItem class.
 * @constructor
 * @member {number} [id]
 * @member {string} [name]
 * @member {boolean} [isComplete]
 */
export interface TodoItem {
  id?: number;
  name?: string;
  isComplete?: boolean;
}
