/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TodoItem.
 */
class TodoItem {
  /**
   * Create a TodoItem.
   * @member {number} [id]
   * @member {string} [name]
   * @member {boolean} [isComplete]
   */
  constructor() {
  }

  /**
   * Defines the metadata of TodoItem
   *
   * @returns {object} metadata of TodoItem
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TodoItem',
      type: {
        name: 'Composite',
        className: 'TodoItem',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          isComplete: {
            required: false,
            serializedName: 'isComplete',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = TodoItem;
